// Package pkcs11 implements a kms.Provider backed by a
// PKCS#11 module — typically a hardware HSM (Thales nCipher,
// Utimaco, AWS CloudHSM, YubiHSM2) or a software emulator
// (SoftHSM2 for testing).  The KEK never leaves the HSM;
// every WrapDEK / UnwrapDEK round-trips through the device.
//
// # KEKRef format
//
//	pkcs11://<token-label>/<key-label>?module=<path>&pin=<pin>&mech=<mechanism>&slot=<id>
//
// Examples:
//
//	pkcs11://prod-token/db-kek?module=/usr/lib/softhsm/libsofthsm2.so&pin=1234
//	pkcs11://prod-token/db-kek-rsa?mech=rsa-oaep&module=/opt/nfast/libcknfast.so&pin_source=/etc/pg_hardstorage/pin
//
// `<token-label>` is the operator-visible PKCS#11 token label
// (CKA_LABEL on the token object).  `<key-label>` is the
// CKA_LABEL on the key object inside that token.  Two label
// strings — operators don't have to memorise slot IDs.
//
// Query parameters:
//
//	module=<path>          # absolute path to the .so / .dll
//	                       # falls back to $PKCS11_MODULE_PATH
//	pin=<value>            # PIN inline; convenient for tests
//	pin_source=<path>      # mode-0600 file containing the PIN;
//	                       # the production path
//	mech=aes-gcm|rsa-oaep  # wrap mechanism; default aes-gcm
//	slot=<id>              # numeric slot id; default
//	                       # auto-resolved from token-label
//
// # Wrap mechanisms
//
//   - aes-gcm  (default) — KEK is a CKK_AES key in the HSM.
//     C_Encrypt with CKM_AES_GCM, fresh 12-byte IV per wrap.
//     Wrapped form: [12-byte IV | ciphertext | 16-byte GCM tag].
//   - rsa-oaep — KEK is an RSA key pair in the HSM.
//     C_Encrypt with CKM_RSA_PKCS_OAEP under the public half;
//     UnwrapDEK calls C_Decrypt under the private half.
//     Wrapped form: opaque ciphertext (length = RSA modulus).
//
// # CGo & build tags
//
// PKCS#11 needs CGo to call libpkcs11.  Default builds
// (CGO_ENABLED=0) include this scheme in the registry but
// every operation returns a structured "binary built without
// -tags pkcs11" error.  Operators wanting HSM rebuild with:
//
//	go build -tags pkcs11 ./cmd/pg_hardstorage
//
// or use the official `pg-hardstorage-fips` artifact, which
// is built with -tags pkcs11 by default since FIPS-validated
// HSM-backed envelopes are the canonical FIPS posture.
//
// The build-tagged backend lives in pkcs11_cgo.go; the
// default-build stub lives in pkcs11_stub.go.  Either way
// the always-built shell here defines Provider, the URL
// parser, and the registry self-registration.
//
// # FIPS posture
//
// HSMs are typically FIPS 140-2 / 140-3 validated; the module
// itself is the validated cryptographic boundary.  FIPSMode
// is operator-declared via WithFIPSMode (or the
// `use_fips_mode` config key) — the PKCS#11 standard exposes
// no portable "am I FIPS?" predicate.
//
// # GDPR Art. 17 / crypto-shred
//
// Shred calls C_DestroyObject on the key object handle.
// Real HSMs frequently have additional policy gates
// (operator-card threshold, ACS quorum) that may refuse the
// destroy; those errors propagate wrapped in ErrShredFailed.
package pkcs11

import (
	"context"
	"crypto/rand"
	"errors"
	"fmt"
	"net/url"
	"os"
	"strconv"
	"strings"
	"sync"

	stdkms "github.com/cybertec-postgresql/pg_hardstorage/internal/kms"
)

// Scheme is the KEKRef scheme this provider claims.
const Scheme = "pkcs11"

func init() {
	stdkms.DefaultRegistry.Register(Scheme, builder)
}

// Mechanism enumerates the wrap mechanisms this provider
// supports.  "aes-gcm" is the default (symmetric KEK in HSM,
// most common); "rsa-oaep" is the asymmetric-KEK path.
type Mechanism string

const (
	// MechAESGCM wraps with CKM_AES_GCM.
	MechAESGCM Mechanism = "aes-gcm"
	// MechRSAOAEP wraps with CKM_RSA_PKCS_OAEP.
	MechRSAOAEP Mechanism = "rsa-oaep"
)

// Client is the subset of PKCS#11 operations the Provider
// uses.  Production code wires the cgo-backed realClient (or
// the stub when built without -tags pkcs11); tests inject a
// fake client to exercise wrap/unwrap orchestration without
// linking against libpkcs11.
type Client interface {
	// Encrypt wraps `plaintext` under the named key using the
	// given mechanism.  IV (for aes-gcm) is generated by the
	// caller and supplied — that way the wrapped envelope
	// format is fully deterministic from the Provider layer
	// and the Client never has to know our framing.
	Encrypt(ctx context.Context, mech Mechanism, keyLabel string, iv, plaintext []byte) ([]byte, error)

	// Decrypt unwraps `ciphertext` under the named key.  For
	// aes-gcm the IV is passed through (we strip it from the
	// wrapped envelope before this call).  For rsa-oaep IV is
	// nil.
	Decrypt(ctx context.Context, mech Mechanism, keyLabel string, iv, ciphertext []byte) ([]byte, error)

	// DestroyKey removes the named key object.  HSM policy may
	// refuse; the error is propagated.
	DestroyKey(ctx context.Context, keyLabel string) error

	// DescribeKey returns vendor-defined attributes (CKA_LABEL,
	// CKA_KEY_TYPE, CKA_MODULUS_BITS for RSA, etc.) for the
	// `kms inspect` surface.
	DescribeKey(ctx context.Context, keyLabel string) (map[string]any, error)

	// Close releases the session + finalises the PKCS#11
	// library.  Idempotent.
	Close() error
}

// Provider implements kms.Provider over PKCS#11.
type Provider struct {
	kekRef    string
	tokenLbl  string
	keyLbl    string
	modulePth string
	mechanism Mechanism
	client    Client
	fipsMode  bool

	mu     sync.Mutex
	closed bool
}

// builder is the registry entry-point.
//
// Config keys (in addition to those parsed from the KEKRef):
//
//	pin: ""                  # override the URL's pin / pin_source
//	module: ""               # override the URL's module=
//	use_fips_mode: false     # operator-declared FIPS posture
//	mechanism: ""            # override the URL's mech=
//	slot: 0                  # override the URL's slot=
func builder(ctx context.Context, kekRef string, cfg map[string]any) (stdkms.Provider, error) {
	parsed, err := parseKEKRef(kekRef)
	if err != nil {
		return nil, err
	}

	// Allow cfg map to override URL params — normal precedence
	// for runtime injection (e.g. PIN supplied via secret-manager
	// rather than baked into the KEKRef).
	if v, ok := cfg["module"].(string); ok && v != "" {
		parsed.modulePath = v
	}
	if v, ok := cfg["pin"].(string); ok && v != "" {
		parsed.pin = v
	}
	if v, ok := cfg["mechanism"].(string); ok && v != "" {
		// v27 audit F1: re-validate the mech that arrived via
		// cfg.  The URL parser checks aes-gcm | rsa-oaep but
		// nothing stops a runtime config injecting a bogus
		// string ("des", "rc4") that would surface much later
		// at the first WrapDEK call.  Validate at Open.
		mech := Mechanism(strings.ToLower(v))
		switch mech {
		case MechAESGCM, MechRSAOAEP:
			parsed.mechanism = mech
		default:
			return nil, fmt.Errorf("pkcs11: cfg[mechanism]=%q unsupported (want aes-gcm | rsa-oaep)", v)
		}
	}
	if v, ok := cfg["slot"].(int); ok && v >= 0 {
		parsed.slot = v
		parsed.slotSet = true
	}

	// Resolve PIN: explicit > pin_source file > $PKCS11_PIN env
	// > error.  Production deployments use pin_source; the
	// inline `pin=` form is for testing.
	if parsed.pin == "" && parsed.pinSource != "" {
		body, ferr := os.ReadFile(parsed.pinSource)
		if ferr != nil {
			return nil, fmt.Errorf("pkcs11: read pin_source %q: %w", parsed.pinSource, ferr)
		}
		parsed.pin = strings.TrimSpace(string(body))
	}
	if parsed.pin == "" {
		parsed.pin = os.Getenv("PKCS11_PIN")
	}
	if parsed.pin == "" {
		return nil, errors.New("pkcs11: no PIN (set ?pin=, ?pin_source=, $PKCS11_PIN, or cfg[pin])")
	}

	// Module path: URL > $PKCS11_MODULE_PATH.
	if parsed.modulePath == "" {
		parsed.modulePath = os.Getenv("PKCS11_MODULE_PATH")
	}
	if parsed.modulePath == "" {
		return nil, errors.New("pkcs11: no module path (set ?module=, $PKCS11_MODULE_PATH, or cfg[module])")
	}

	cli, err := newRealClient(ctx, realClientConfig{
		ModulePath: parsed.modulePath,
		TokenLabel: parsed.tokenLabel,
		PIN:        parsed.pin,
		Slot:       parsed.slot,
		SlotSet:    parsed.slotSet,
	})
	if err != nil {
		return nil, fmt.Errorf("pkcs11: open client: %w", err)
	}

	fipsMode, _ := cfg["use_fips_mode"].(bool)

	return &Provider{
		kekRef:    kekRef,
		tokenLbl:  parsed.tokenLabel,
		keyLbl:    parsed.keyLabel,
		modulePth: parsed.modulePath,
		mechanism: parsed.mechanism,
		client:    cli,
		fipsMode:  fipsMode,
	}, nil
}

// realClientConfig is the cross-build shape consumed by both
// the cgo and stub realClient constructors.
type realClientConfig struct {
	ModulePath string
	TokenLabel string
	PIN        string
	Slot       int
	SlotSet    bool
}

// NewWithClient is the test-friendly constructor — pass any
// Client implementation (real HSM, fake, recorder).
func NewWithClient(kekRef string, client Client, opts ...Option) (*Provider, error) {
	parsed, err := parseKEKRef(kekRef)
	if err != nil {
		return nil, err
	}
	p := &Provider{
		kekRef:    kekRef,
		tokenLbl:  parsed.tokenLabel,
		keyLbl:    parsed.keyLabel,
		modulePth: parsed.modulePath,
		mechanism: parsed.mechanism,
		client:    client,
	}
	for _, o := range opts {
		o(p)
	}
	return p, nil
}

// Option tunes NewWithClient.
type Option func(*Provider)

// WithFIPSMode declares the provider's FIPS posture.
func WithFIPSMode(fips bool) Option { return func(p *Provider) { p.fipsMode = fips } }

// Name implements kms.Provider.
func (p *Provider) Name() string { return Scheme }

// KEKRef implements kms.Provider.
func (p *Provider) KEKRef() string { return p.kekRef }

// FIPSMode implements kms.Provider.
func (p *Provider) FIPSMode() bool { return p.fipsMode }

// Mechanism returns the configured wrap mechanism.  Used by
// the operator-facing inspector.
func (p *Provider) Mechanism() Mechanism { return p.mechanism }

// WrapDEK implements kms.Provider.
//
// AES-GCM path (default): fresh 12-byte random IV; HSM
// performs the AEAD; wrapped envelope is `IV || cipher+tag`.
//
// RSA-OAEP path: HSM wraps the DEK directly under the public
// key; wrapped envelope is the raw RSA-modulus-sized
// ciphertext.
func (p *Provider) WrapDEK(ctx context.Context, dek []byte) ([]byte, error) {
	if err := p.assertOpen(); err != nil {
		return nil, err
	}
	switch p.mechanism {
	case MechAESGCM:
		iv := make([]byte, aesGCMIVLen)
		if _, err := rand.Read(iv); err != nil {
			return nil, fmt.Errorf("pkcs11: generate IV: %w", err)
		}
		ct, err := p.client.Encrypt(ctx, p.mechanism, p.keyLbl, iv, dek)
		if err != nil {
			return nil, fmt.Errorf("pkcs11: aes-gcm wrap: %w", err)
		}
		// Frame: IV || ciphertext+tag.
		envelope := make([]byte, 0, aesGCMIVLen+len(ct))
		envelope = append(envelope, iv...)
		envelope = append(envelope, ct...)
		return envelope, nil
	case MechRSAOAEP:
		ct, err := p.client.Encrypt(ctx, p.mechanism, p.keyLbl, nil, dek)
		if err != nil {
			return nil, fmt.Errorf("pkcs11: rsa-oaep wrap: %w", err)
		}
		return ct, nil
	default:
		return nil, fmt.Errorf("pkcs11: unsupported mechanism %q", p.mechanism)
	}
}

// UnwrapDEK implements kms.Provider.
func (p *Provider) UnwrapDEK(ctx context.Context, wrapped []byte) ([]byte, error) {
	if err := p.assertOpen(); err != nil {
		return nil, err
	}
	switch p.mechanism {
	case MechAESGCM:
		if len(wrapped) < aesGCMIVLen+aesGCMTagLen {
			return nil, fmt.Errorf("%w: aes-gcm envelope too short (%d bytes)",
				stdkms.ErrUnwrap, len(wrapped))
		}
		iv := wrapped[:aesGCMIVLen]
		ct := wrapped[aesGCMIVLen:]
		dek, err := p.client.Decrypt(ctx, p.mechanism, p.keyLbl, iv, ct)
		if err != nil {
			return nil, fmt.Errorf("%w: aes-gcm unwrap: %v", stdkms.ErrUnwrap, err)
		}
		return dek, nil
	case MechRSAOAEP:
		dek, err := p.client.Decrypt(ctx, p.mechanism, p.keyLbl, nil, wrapped)
		if err != nil {
			return nil, fmt.Errorf("%w: rsa-oaep unwrap: %v", stdkms.ErrUnwrap, err)
		}
		return dek, nil
	default:
		return nil, fmt.Errorf("%w: unsupported mechanism %q",
			stdkms.ErrUnwrap, p.mechanism)
	}
}

// Shred implements kms.Provider.  Calls C_DestroyObject on
// the named key.  HSM policy may refuse with an operator-
// quorum or partition-card requirement; the error wraps
// ErrShredFailed so callers can distinguish from network
// failures.
func (p *Provider) Shred(ctx context.Context) error {
	if err := p.assertOpen(); err != nil {
		return err
	}
	if err := p.client.DestroyKey(ctx, p.keyLbl); err != nil {
		return fmt.Errorf("%w: DestroyKey %q: %v",
			stdkms.ErrShredFailed, p.keyLbl, err)
	}
	return nil
}

// Close implements kms.Provider.
func (p *Provider) Close() error {
	p.mu.Lock()
	defer p.mu.Unlock()
	if p.closed {
		return nil
	}
	p.closed = true
	return p.client.Close()
}

// DescribeKey is the operator-facing inspector used by
// `kms inspect`.
func (p *Provider) DescribeKey(ctx context.Context) (map[string]any, error) {
	if err := p.assertOpen(); err != nil {
		return nil, err
	}
	body, err := p.client.DescribeKey(ctx, p.keyLbl)
	if err != nil {
		return nil, fmt.Errorf("pkcs11: DescribeKey: %w", err)
	}
	if body == nil {
		body = map[string]any{}
	}
	body["token_label"] = p.tokenLbl
	body["key_label"] = p.keyLbl
	body["module_path"] = p.modulePth
	body["mechanism"] = string(p.mechanism)
	return body, nil
}

func (p *Provider) assertOpen() error {
	p.mu.Lock()
	defer p.mu.Unlock()
	if p.closed {
		return errors.New("pkcs11: provider closed")
	}
	return nil
}

// AES-GCM constants.  These are part of the wrap-envelope
// schema and frozen for the 24-month compatibility window.
const (
	aesGCMIVLen  = 12
	aesGCMTagLen = 16
)

// parsedRef is the broken-down form of a pkcs11:// KEKRef.
type parsedRef struct {
	tokenLabel string
	keyLabel   string
	modulePath string
	pin        string
	pinSource  string
	mechanism  Mechanism
	slot       int
	slotSet    bool
}

// parseKEKRef extracts the token + key + query parameters
// from a pkcs11:// URL.
//
//	pkcs11://<token>/<key>?module=...&pin=...&mech=...&slot=...
//
// Labels use the alphabet RFC 3986 permits in the host +
// path-segment positions: ASCII letters, digits, "-", "_",
// ".".  Operators with HSM labels containing whitespace or
// non-ASCII characters rename the keys; the URL form is
// deliberately straightforward.
func parseKEKRef(kekRef string) (parsedRef, error) {
	if !strings.HasPrefix(kekRef, Scheme+"://") {
		return parsedRef{}, fmt.Errorf("pkcs11: KEKRef %q does not have the %q:// prefix", kekRef, Scheme)
	}
	u, err := url.Parse(kekRef)
	if err != nil {
		return parsedRef{}, fmt.Errorf("pkcs11: parse KEKRef %q: %w", kekRef, err)
	}
	if u.Scheme != Scheme {
		return parsedRef{}, fmt.Errorf("pkcs11: KEKRef scheme %q, want %q", u.Scheme, Scheme)
	}
	tokenLabel := u.Host
	if tokenLabel == "" {
		return parsedRef{}, fmt.Errorf("pkcs11: empty token label in %q", kekRef)
	}
	keyPath := strings.TrimPrefix(u.Path, "/")
	if keyPath == "" {
		return parsedRef{}, fmt.Errorf("pkcs11: empty key label in %q", kekRef)
	}
	if strings.Contains(keyPath, "/") {
		return parsedRef{}, fmt.Errorf("pkcs11: key label %q must not contain '/'", keyPath)
	}
	keyLabel := keyPath

	q := u.Query()
	mech := Mechanism(strings.ToLower(q.Get("mech")))
	if mech == "" {
		mech = MechAESGCM
	}
	switch mech {
	case MechAESGCM, MechRSAOAEP:
		// ok
	default:
		return parsedRef{}, fmt.Errorf("pkcs11: unsupported mech %q (want aes-gcm | rsa-oaep)", mech)
	}

	out := parsedRef{
		tokenLabel: tokenLabel,
		keyLabel:   keyLabel,
		modulePath: q.Get("module"),
		pin:        q.Get("pin"),
		pinSource:  q.Get("pin_source"),
		mechanism:  mech,
	}
	if s := q.Get("slot"); s != "" {
		n, err := strconv.Atoi(s)
		if err != nil || n < 0 {
			return parsedRef{}, fmt.Errorf("pkcs11: bad slot %q", s)
		}
		out.slot = n
		out.slotSet = true
	}
	return out, nil
}
