package repo_test

// gc_tombstone_scope_test.go — GC's tombstone set was keyed on the
// backup ID alone, not on (deployment, backup ID).
//
// CollectReferences builds `tombstoned` from
// manifests/<dep>/backups/<id>/manifest.json.tombstone using parts[3]
// (the id) and nothing else, then skips any live manifest whose parts[3]
// is in that set. So a tombstone in deployment A suppresses a LIVE
// manifest carrying the same id in deployment B — its chunks drop out of
// the reference set, FindOrphans reports them unreferenced, and
// `repo gc --apply` deletes the chunks of a backup nobody deleted.
//
// Today the IDs generated by the backup runner are
// "<deployment>.<type>.<ts>.<rand>", so a collision cannot arise from
// normal use. But nothing ENFORCES that: Manifest.Validate checks that
// BackupID and Deployment are each non-empty and that parent != self,
// and never relates them. The safety of the most destructive path in the
// repository therefore rested on a naming convention rather than on a
// structural property — and the comment two lines above the skip claims
// "silent data loss is impossible".
//
// Keying on deployment + id makes the property hold by construction and
// costs nothing. It also does not impose an ID format, so custom or
// legacy ids written by an integration keep working.

import (
	"context"
	"testing"

	"github.com/cybertec-postgresql/pg_hardstorage/internal/plugin/storage"
	"github.com/cybertec-postgresql/pg_hardstorage/internal/repo"
)

func TestCollectReferences_TombstoneDoesNotCrossDeployments(t *testing.T) {
	sp, cas := newGCRepo(t)
	ctx := context.Background()

	live, err := cas.PutChunk(ctx, []byte("only-referenced-by-db2"))
	if err != nil {
		t.Fatal(err)
	}
	dead, err := cas.PutChunk(ctx, []byte("only-referenced-by-db1"))
	if err != nil {
		t.Fatal(err)
	}

	// Same backup ID in two deployments. db1's copy is tombstoned;
	// db2's is live and is the only referent of `live`.
	const id = "shared-id"
	put := func(key, body string) {
		t.Helper()
		if _, err := sp.Put(ctx, key, readerOf(body),
			storage.PutOptions{ContentLength: int64(len(body))}); err != nil {
			t.Fatalf("put %s: %v", key, err)
		}
	}
	put("manifests/db1/backups/"+id+"/manifest.json",
		`{"files":[{"chunks":[{"hash":"`+dead.Hash.String()+`"}]}]}`)
	put("manifests/db1/backups/"+id+"/manifest.json.tombstone",
		`{"schema":"pg_hardstorage.tombstone.v1"}`)
	put("manifests/db2/backups/"+id+"/manifest.json",
		`{"files":[{"chunks":[{"hash":"`+live.Hash.String()+`"}]}]}`)

	refs, err := repo.CollectReferencesWithOptions(ctx, sp,
		repo.CollectReferencesOptions{TombstoneGrace: -1})
	if err != nil {
		t.Fatal(err)
	}
	if !refs.Has(live.Hash) {
		t.Fatalf("db2's live manifest was suppressed by db1's tombstone.\n\n"+
			"Its chunk %s is now unreferenced, so `repo gc --apply` deletes the data of a "+
			"backup nobody deleted — in a different deployment. The tombstone set is keyed "+
			"on the backup ID alone.", live.Hash)
	}

	// And the genuinely tombstoned one must still be collected.
	if refs.Has(dead.Hash) {
		t.Error("db1's tombstoned manifest still contributed a reference; the scope fix must " +
			"not stop tombstones working within their own deployment")
	}

	orphans, err := repo.FindOrphans(ctx, sp, refs)
	if err != nil {
		t.Fatal(err)
	}
	if len(orphans) != 1 || orphans[0] != dead.Hash {
		t.Errorf("orphans = %v, want exactly the tombstoned deployment's chunk %s",
			orphans, dead.Hash)
	}
}

// The ordinary same-deployment case must keep working exactly as before.
func TestCollectReferences_TombstoneStillAppliesWithinItsDeployment(t *testing.T) {
	sp, cas := newGCRepo(t)
	ctx := context.Background()
	a, err := cas.PutChunk(ctx, []byte("tombstoned-chunk"))
	if err != nil {
		t.Fatal(err)
	}
	body := `{"files":[{"chunks":[{"hash":"` + a.Hash.String() + `"}]}]}`
	if _, err := sp.Put(ctx, "manifests/db1/backups/b1/manifest.json", readerOf(body),
		storage.PutOptions{ContentLength: int64(len(body))}); err != nil {
		t.Fatal(err)
	}
	tomb := `{"schema":"pg_hardstorage.tombstone.v1"}`
	if _, err := sp.Put(ctx, "manifests/db1/backups/b1/manifest.json.tombstone", readerOf(tomb),
		storage.PutOptions{ContentLength: int64(len(tomb))}); err != nil {
		t.Fatal(err)
	}
	refs, err := repo.CollectReferencesWithOptions(ctx, sp,
		repo.CollectReferencesOptions{TombstoneGrace: -1})
	if err != nil {
		t.Fatal(err)
	}
	if refs.Len() != 0 {
		t.Errorf("a tombstoned manifest still contributed %d reference(s) in its own deployment",
			refs.Len())
	}
}
