// Package translate converts a pgbackrest.conf INI file into
// a pg_hardstorage.yaml configuration.
//
// The mapping is intentionally lossy: pgBackRest knobs that
// have a direct semantic equivalent in pg_hardstorage are
// translated; everything else is emitted as a YAML comment
// with a stderr summary so the operator can review what
// didn't make it across.
//
// See compat/pgbackrest/flags.go for the shared mapping
// table; this package only handles the INI→YAML round trip.
package translate

import (
	"bufio"
	"fmt"
	"io"
	"sort"
	"strings"
)

// Section is one [section] in the INI file.
type Section struct {
	Name string
	KV   map[string]string
}

// Config is the parsed INI representation.
type Config struct {
	Sections []*Section
}

// Parse reads a pgbackrest.conf-shaped INI document.  Comments
// (`#` or `;` to end-of-line) are stripped; blank lines are
// dropped.  Section headers are case-sensitive (pgBackRest's
// convention).
func Parse(r io.Reader) (*Config, error) {
	cfg := &Config{}
	var current *Section
	scanner := bufio.NewScanner(r)
	scanner.Buffer(make([]byte, 64*1024), 1024*1024)
	lineno := 0
	for scanner.Scan() {
		lineno++
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "#") || strings.HasPrefix(line, ";") {
			continue
		}
		// Strip end-of-line comments.
		for _, sep := range []string{" #", "\t#"} {
			if i := strings.Index(line, sep); i >= 0 {
				line = strings.TrimSpace(line[:i])
			}
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			name := strings.TrimSpace(line[1 : len(line)-1])
			current = &Section{Name: name, KV: map[string]string{}}
			cfg.Sections = append(cfg.Sections, current)
			continue
		}
		if current == nil {
			return nil, fmt.Errorf("line %d: key/value before any [section] header", lineno)
		}
		eq := strings.Index(line, "=")
		if eq < 0 {
			return nil, fmt.Errorf("line %d: missing '=' in %q", lineno, line)
		}
		key := strings.TrimSpace(line[:eq])
		val := strings.TrimSpace(line[eq+1:])
		current.KV[key] = val
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scanning input: %w", err)
	}
	return cfg, nil
}

// Result is what Translate returns.  YAML is the rendered
// pg_hardstorage.yaml; Unmapped is the list of "we saw this
// key but had nothing to do with it" entries (one per
// section.key); Warnings are semantic-equivalence notes
// (algorithm differs, async ignored, ...).
type Result struct {
	YAML     string
	Unmapped []string
	Warnings []string
}

// Translate converts the parsed INI to a pg_hardstorage YAML
// document.  Each non-global section becomes one deployment.
func Translate(cfg *Config) (*Result, error) {
	if cfg == nil {
		return &Result{}, nil
	}
	out := &Result{}
	var globalKV map[string]string
	for _, s := range cfg.Sections {
		if strings.EqualFold(s.Name, "global") {
			globalKV = s.KV
			break
		}
	}
	if globalKV == nil {
		globalKV = map[string]string{}
	}

	var b strings.Builder
	b.WriteString("# Generated by pg_hardstorage compat translate --from pgbackrest\n")
	b.WriteString("# Review every block before activating; semantic notes are above each line.\n")
	b.WriteString("\n")
	b.WriteString("deployments:\n")

	for _, s := range cfg.Sections {
		if strings.EqualFold(s.Name, "global") {
			continue
		}
		writeDeployment(&b, s, globalKV, out)
	}

	// Global-only options worth surfacing as YAML comments.
	for _, k := range sortedKeys(globalKV) {
		switch k {
		case "repo1-cipher-pass", "repo1-cipher-type",
			"repo1-type", "repo1-path", "repo1-s3-bucket",
			"repo1-s3-region", "repo1-s3-endpoint",
			"compress-type", "retention-full":
			// Picked up per-deployment.
		default:
			out.Unmapped = append(out.Unmapped,
				fmt.Sprintf("[global] %s = %s", k, globalKV[k]))
		}
	}

	out.YAML = b.String()
	return out, nil
}

func writeDeployment(b *strings.Builder, s *Section, global map[string]string, r *Result) {
	resolve := func(k string) string {
		if v, ok := s.KV[k]; ok {
			return v
		}
		return global[k]
	}

	// config.Load decodes `deployments:` as map[string]DeploymentConfig
	// (KnownFields(true)), so each deployment must be a MAPPING keyed by
	// its name — not a `- name:` sequence item.
	fmt.Fprintf(b, "  %s:\n", s.Name)

	// PG connection
	host := resolve("pg1-host")
	port := resolve("pg1-port")
	db := resolve("pg1-database")
	user := resolve("pg1-user")
	if host != "" {
		if user == "" {
			user = "postgres"
		}
		if db == "" {
			db = "postgres"
		}
		conn := fmt.Sprintf("postgres://%s@%s", user, host)
		if port != "" {
			conn += ":" + port
		}
		conn += "/" + db
		fmt.Fprintf(b, "    pg_connection: %q\n", conn)
	}

	// Repo URL
	repoType := strings.ToLower(resolve("repo1-type"))
	switch repoType {
	case "", "posix":
		if path := resolve("repo1-path"); path != "" {
			fmt.Fprintf(b, "    repo: %q\n", "file://"+path)
		}
	case "s3":
		bucket := resolve("repo1-s3-bucket")
		prefix := strings.TrimLeft(resolve("repo1-path"), "/")
		if bucket != "" {
			url := "s3://" + bucket
			if prefix != "" {
				url += "/" + prefix
			}
			fmt.Fprintf(b, "    repo: %q\n", url)
			r.Warnings = append(r.Warnings,
				"["+s.Name+"] AWS credentials must be supplied via the standard SDK chain (env, IRSA, profile)")
		}
	default:
		r.Unmapped = append(r.Unmapped,
			fmt.Sprintf("[%s] repo1-type = %s (unsupported)", s.Name, repoType))
	}

	// Cipher
	if cipher := strings.ToLower(resolve("repo1-cipher-type")); cipher == "aes-256-cbc" {
		if pass := resolve("repo1-cipher-pass"); pass != "" {
			fmt.Fprintln(b,
				"    # repo1-cipher-type=aes-256-cbc -> native AES-256-GCM with KEK derivation; algorithm differs.")
			fmt.Fprintln(b, "    encryption:")
			fmt.Fprintln(b, "      kek_ref: \"local:default\"")
			fmt.Fprintln(b, "      passphrase_env: PG_HARDSTORAGE_KEK_PASSPHRASE")
			r.Warnings = append(r.Warnings,
				"["+s.Name+"] aes-256-cbc maps to AES-256-GCM; set PG_HARDSTORAGE_KEK_PASSPHRASE before first run")
		}
	}

	// Compression
	switch strings.ToLower(resolve("compress-type")) {
	case "", "zstd":
		// Native default; no emit needed.
	case "lz4", "gzip":
		fmt.Fprintf(b,
			"    # compress-type=%s ignored; native uses zstd by default.\n",
			resolve("compress-type"))
		r.Warnings = append(r.Warnings,
			fmt.Sprintf("[%s] compress-type=%s ignored; native uses zstd",
				s.Name, resolve("compress-type")))
	}

	// Retention
	if rf := resolve("retention-full"); rf != "" {
		fmt.Fprintln(b, "    retention:")
		fmt.Fprintln(b, "      policy: count")
		fmt.Fprintf(b, "      keep_full_count: %s\n", rf)
	}

	// Per-section unknowns
	for _, k := range sortedKeys(s.KV) {
		switch k {
		case "pg1-host", "pg1-port", "pg1-database", "pg1-user",
			"repo1-type", "repo1-path",
			"repo1-s3-bucket", "repo1-s3-region", "repo1-s3-endpoint",
			"repo1-cipher-type", "repo1-cipher-pass",
			"compress-type", "retention-full":
			// handled above
		default:
			r.Unmapped = append(r.Unmapped,
				fmt.Sprintf("[%s] %s = %s", s.Name, k, s.KV[k]))
		}
	}
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
