d /var/lib/pg_hardstorage 0750 pgbackup pgbackup -
d /var/lib/pg_hardstorage/inflight 0750 pgbackup pgbackup -
d /var/lib/pg_hardstorage/crashes 0750 pgbackup pgbackup -
d /var/cache/pg_hardstorage 0750 pgbackup pgbackup -
d /var/log/pg_hardstorage 0750 pgbackup pgbackup -
d /run/pg_hardstorage 0750 pgbackup pgbackup -
d /etc/pg_hardstorage 0755 root root -
d /etc/pg_hardstorage/deployments 0750 root pgbackup -
d /etc/pg_hardstorage/conf.d 0755 root root -
d /etc/pg_hardstorage/keyring 0700 pgbackup pgbackup -
