package translate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestSampleBarmanConfRoundTrip parses testdata/sample-barman.conf
// and asserts that the emitted YAML contains the expected mapped
// keys and that every unmapped Barman setting surfaces in the
// summary.
func TestSampleBarmanConfRoundTrip(t *testing.T) {
	path := filepath.Join("testdata", "sample-barman.conf")
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer f.Close()

	got, err := Translate(f)
	if err != nil {
		t.Fatalf("Translate: %v", err)
	}

	// Key claims that must hold for the test fixture.
	mustContain := []string{
		"deployments:",
		"name: db1",
		"name: db2-reporting",
		"connection: ", // streaming_conninfo gets collapsed onto connection:
		"description:",
		"slot:",
		"name: barman_db1",
		"create: auto",
		"parallelism: 4",
		"compression:",
		"algorithm: zstd",
		"retention:",
		"keep_for: 7 days",
		"keep_full: 4",
		"minimum_redundancy: 2",
		`repo: "file:///var/lib/barman/db1"`,
		`repo: "file:///mnt/nfs/barman/db2-reporting"`,
		"backup:",
		"fast: false",
	}
	for _, want := range mustContain {
		if !strings.Contains(got.YAML, want) {
			t.Errorf("YAML missing %q\n--- yaml ---\n%s", want, got.YAML)
		}
	}

	// Drop checks: refused settings must NOT appear as a live YAML
	// line (only as a "# ..." comment).  Walk line-by-line so the
	// elided-as-comment notes don't trip the assertion.
	bannedLive := []string{
		"backup_method:",
	}
	for _, line := range strings.Split(got.YAML, "\n") {
		trimmed := strings.TrimLeft(line, " \t")
		if strings.HasPrefix(trimmed, "#") {
			continue
		}
		for _, banned := range bannedLive {
			if strings.Contains(trimmed, banned) {
				t.Errorf("YAML emitted live %q line: %q", banned, line)
			}
		}
	}

	// Unmapped summary must mention the expected entries — both
	// "no v1.1 mapping" leftovers and explicit drops.
	wantUnmapped := map[string]string{
		"custom_unmapped_setting": "no v1.1 mapping",
		"retry_times":             "exponential backoff",
		"backup_method":           "rsync",
		"pre_backup_script":       "notify",
		"archive_command":         "PG-side",
		"archive_mode":            "PG-side",
	}
	for key, fragment := range wantUnmapped {
		var found bool
		for _, u := range got.Unmapped {
			if u.Key == key && strings.Contains(u.Reason, fragment) {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("Unmapped summary missing key=%q reason~=%q", key, fragment)
		}
	}

	// Provenance header must be present.
	if !strings.HasPrefix(got.YAML, "# Generated by") {
		t.Errorf("YAML missing provenance header; got first line %q",
			firstLine(got.YAML))
	}
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}

// TestParseINI exercises the INI parser's quirks: comments,
// continuations, key=value AND key:value, mixed comment markers.
func TestParseINI(t *testing.T) {
	src := strings.NewReader(`
; comment one
# comment two
[barman]
log_level = INFO
[db1]
description: A multi
    line description
conninfo=host=foo dbname=bar
`)
	doc, err := parseINI(src)
	if err != nil {
		t.Fatalf("parseINI: %v", err)
	}
	if len(doc.sections) != 2 {
		t.Fatalf("want 2 sections, got %d", len(doc.sections))
	}
	if got := doc.sections[1].pairs["description"]; !strings.Contains(got, "A multi") || !strings.Contains(got, "line description") {
		t.Errorf("continuation join failed: %q", got)
	}
	if got := doc.sections[1].pairs["conninfo"]; got != "host=foo dbname=bar" {
		t.Errorf("k=v parsing: got %q", got)
	}
}
