package translate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestSampleBarmanConfRoundTrip parses testdata/sample-barman.conf
// and asserts that the emitted YAML contains the expected mapped
// keys and that every unmapped Barman setting surfaces in the
// summary.
func TestSampleBarmanConfRoundTrip(t *testing.T) {
	path := filepath.Join("testdata", "sample-barman.conf")
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer f.Close()

	got, err := Translate(f)
	if err != nil {
		t.Fatalf("Translate: %v", err)
	}

	// Key claims that must hold for the test fixture. Deployments are
	// emitted as a MAPPING keyed by name (config.Load decodes
	// `deployments:` as map[string]DeploymentConfig, KnownFields(true)),
	// so we assert `  <name>:` map keys, not `- name:` sequence items.
	mustContain := []string{
		"deployments:",
		"  db1:",
		"  db2-reporting:",
		// conninfo -> pg_connection (the native field name); the paired
		// streaming_conninfo collapses onto the same key (see below).
		`pg_connection: "host=db1.example.com user=barman dbname=postgres"`,
		"slot:",
		"name: barman_db1",
		"parallelism: 4",
		"compression:",
		"algorithm: zstd",
		"retention:",
		// RECOVERY WINDOW OF 7 DAYS -> time.ParseDuration-compatible 168h
		// (the agent rejects "7 days"); REDUNDANCY 4 -> keep_fulls (the
		// config field name is keep_fulls, not keep_full).
		"keep_for: 168h",
		"keep_fulls: 4",
		`repo: "file:///var/lib/barman/db1"`,
		`repo: "file:///mnt/nfs/barman/db2-reporting"`,
		"backup:",
		"fast: false",
	}
	for _, want := range mustContain {
		if !strings.Contains(got.YAML, want) {
			t.Errorf("YAML missing %q\n--- yaml ---\n%s", want, got.YAML)
		}
	}

	// Field-name / duplicate-key correctness (bug #9): the loader uses
	// the field `pg_connection`, never `connection:`, and rejects
	// duplicate mapping keys. streaming_conninfo, create_slot, and
	// minimum_redundancy each pair with an earlier key onto the same
	// native top-level key, so they must be collapsed to comments —
	// never re-emitted as a live duplicate. Also assert the buggy
	// `--to-backup`-era field names are gone.
	bannedLive := []string{
		"connection:", // must be pg_connection, not connection
		"keep_full:",  // must be keep_fulls
		"minimum_redundancy:",
		"description:",   // native has no description field
		"backup_method:", // refused method must be a comment, not live
	}
	for _, line := range strings.Split(got.YAML, "\n") {
		trimmed := strings.TrimLeft(line, " \t")
		if strings.HasPrefix(trimmed, "#") {
			continue
		}
		for _, banned := range bannedLive {
			if strings.HasPrefix(trimmed, banned) {
				t.Errorf("YAML emitted live %q line: %q", banned, line)
			}
		}
	}
	// Exactly one pg_connection per deployment (no duplicate key from
	// conninfo + streaming_conninfo).
	if n := strings.Count(got.YAML, "pg_connection:") - strings.Count(got.YAML, "# streaming_conninfo"); n != 2 {
		// db1 (conninfo) + db2-reporting (conninfo) = 2 live keys.
		t.Errorf("want 2 live pg_connection keys, got %d\n--- yaml ---\n%s", n, got.YAML)
	}

	// Unmapped summary must mention the expected entries — both
	// "no v1.1 mapping" leftovers and explicit drops.
	wantUnmapped := map[string]string{
		"custom_unmapped_setting": "no v1.1 mapping",
		"retry_times":             "exponential backoff",
		"backup_method":           "rsync",
		"pre_backup_script":       "notify",
		"archive_command":         "PG-side",
		"archive_mode":            "PG-side",
	}
	for key, fragment := range wantUnmapped {
		var found bool
		for _, u := range got.Unmapped {
			if u.Key == key && strings.Contains(u.Reason, fragment) {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("Unmapped summary missing key=%q reason~=%q", key, fragment)
		}
	}

	// Provenance header must be present.
	if !strings.HasPrefix(got.YAML, "# Generated by") {
		t.Errorf("YAML missing provenance header; got first line %q",
			firstLine(got.YAML))
	}
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}

// TestParseINI exercises the INI parser's quirks: comments,
// continuations, key=value AND key:value, mixed comment markers.
func TestParseINI(t *testing.T) {
	src := strings.NewReader(`
; comment one
# comment two
[barman]
log_level = INFO
[db1]
description: A multi
    line description
conninfo=host=foo dbname=bar
`)
	doc, err := parseINI(src)
	if err != nil {
		t.Fatalf("parseINI: %v", err)
	}
	if len(doc.sections) != 2 {
		t.Fatalf("want 2 sections, got %d", len(doc.sections))
	}
	if got := doc.sections[1].pairs["description"]; !strings.Contains(got, "A multi") || !strings.Contains(got, "line description") {
		t.Errorf("continuation join failed: %q", got)
	}
	if got := doc.sections[1].pairs["conninfo"]; got != "host=foo dbname=bar" {
		t.Errorf("k=v parsing: got %q", got)
	}
}
