// translate.go — Barman INI → pg_hardstorage YAML renderer: orchestrates parse + mapping table + comment-preserving emit.
package translate

import (
	"fmt"
	"io"
	"sort"
	"strings"
)

// Result is the outcome of a translate run: the rendered YAML, plus
// a list of unmapped settings the caller surfaces to stderr.
type Result struct {
	YAML     string
	Unmapped []Unmapped
}

// Unmapped is one Barman setting that had no native equivalent.
// Section is empty for global ([barman]) settings; otherwise the
// per-server section name.
type Unmapped struct {
	Section string
	Key     string
	Value   string
	Reason  string
}

// Translate reads a Barman INI from r and emits a pg_hardstorage
// YAML deployment file.  Multiple sections become multiple
// deployments under top-level `deployments:`.
//
// Mapping rules live in mapping.go; the renderer is dumb on top of
// the rules table.  YAML output is hand-rolled (rather than
// gopkg.in/yaml.v3) so we can interleave comments for unmapped
// settings without the round-trip mangling marshal/unmarshal does
// to comment trivia.
func Translate(r io.Reader) (*Result, error) {
	doc, err := parseINI(r)
	if err != nil {
		return nil, err
	}

	out := &Result{}
	var b strings.Builder

	// Header — provenance for the operator who diffs the file later.
	b.WriteString("# Generated by `pg_hardstorage compat translate --from barman`.\n")
	b.WriteString("# Review carefully before deploying — unmapped Barman settings are\n")
	b.WriteString("# preserved as comments and surface in the translator's stderr summary.\n\n")

	// Global [barman] settings — only a few have deployment-level
	// equivalents.  We render any global mappings as top-level
	// fields if present; otherwise we just collect unmapped notes.
	var deployments []*iniSection
	for _, sec := range doc.sections {
		if strings.EqualFold(sec.name, "barman") {
			emitGlobal(&b, sec, &out.Unmapped)
		} else {
			deployments = append(deployments, sec)
		}
	}

	if len(deployments) == 0 {
		b.WriteString("# No per-server [<name>] sections found in the source file.\n")
		out.YAML = b.String()
		return out, nil
	}

	b.WriteString("deployments:\n")
	for _, sec := range deployments {
		emitDeployment(&b, sec, &out.Unmapped)
	}

	out.YAML = b.String()
	return out, nil
}

// emitGlobal renders settings from the [barman] section.  v1.1 has
// no top-level pg_hardstorage YAML field that maps cleanly from any
// of these, so every non-trivial key becomes an Unmapped entry —
// the renderer drops them in a header comment block.
func emitGlobal(b *strings.Builder, sec *iniSection, un *[]Unmapped) {
	if len(sec.keys) == 0 {
		return
	}
	b.WriteString("# [barman] global settings (carried as comments — no top-level\n")
	b.WriteString("# pg_hardstorage equivalents in v1.1):\n")
	for _, k := range sec.keys {
		v := sec.pairs[k]
		b.WriteString("#   ")
		b.WriteString(k)
		b.WriteString(" = ")
		b.WriteString(v)
		b.WriteString("\n")
		*un = append(*un, Unmapped{
			Section: "",
			Key:     k,
			Value:   v,
			Reason:  "no top-level pg_hardstorage equivalent",
		})
	}
	b.WriteString("\n")
}

// emitDeployment renders one [<server>] section as one entry under
// top-level `deployments:`.
func emitDeployment(b *strings.Builder, sec *iniSection, un *[]Unmapped) {
	// config.Load decodes `deployments:` as map[string]DeploymentConfig
	// (KnownFields(true)), so each deployment must be a MAPPING keyed by
	// its name — not a `- name:` sequence item. Emit `  <name>:` and nest
	// the deployment's fields one level deeper.
	fmt.Fprintf(b, "  %s:\n", yamlString(sec.name))

	// Two passes: known-mapped first (so the YAML reads predictably),
	// then unmapped settings as comments under the deployment.
	//
	// Several Barman keys collapse onto the SAME native top-level key
	// (conninfo + streaming_conninfo → pg_connection; slot_name +
	// create_slot → slot; retention_policy + minimum_redundancy →
	// retention). YAML forbids duplicate keys in a mapping and the
	// strict loader would reject the file, so we emit each top-level
	// key at most once — the first Barman key wins and any later key
	// that would re-emit it is preserved as a comment for the operator.
	known := map[string]bool{}
	emittedTopKey := map[string]bool{}
	for _, k := range sec.keys {
		row, ok := mappingByKey[k]
		if !ok {
			continue
		}
		v := sec.pairs[k]
		rendered, drop, reason := row.render(v)
		if drop {
			*un = append(*un, Unmapped{
				Section: sec.name,
				Key:     k,
				Value:   v,
				Reason:  reason,
			})
			fmt.Fprintf(b, "    # %s = %s  (%s)\n", k, v, reason)
			known[k] = true
			continue
		}
		// Dedup by the block's top-level YAML key. If a prior Barman
		// setting already emitted this native key, don't emit it a
		// second time (would produce a duplicate mapping key); comment
		// the collapse instead.
		if top := topLevelKey(rendered); top != "" {
			if emittedTopKey[top] {
				fmt.Fprintf(b, "    # %s = %s  (collapsed into earlier %s:)\n", k, v, top)
				*un = append(*un, Unmapped{
					Section: sec.name,
					Key:     k,
					Value:   v,
					Reason:  fmt.Sprintf("collapsed into earlier %s:", top),
				})
				known[k] = true
				continue
			}
			emittedTopKey[top] = true
		}
		// rendered may be multiple lines (e.g. a nested block).
		for _, line := range strings.Split(strings.TrimRight(rendered, "\n"), "\n") {
			b.WriteString("    ")
			b.WriteString(line)
			b.WriteString("\n")
		}
		known[k] = true
	}

	// Anything we didn't know how to map → comment block.
	var leftover []string
	for _, k := range sec.keys {
		if known[k] {
			continue
		}
		leftover = append(leftover, k)
	}
	if len(leftover) > 0 {
		sort.Strings(leftover)
		b.WriteString("    # unmapped Barman settings (review):\n")
		for _, k := range leftover {
			v := sec.pairs[k]
			fmt.Fprintf(b, "    #   %s = %s\n", k, v)
			*un = append(*un, Unmapped{
				Section: sec.name,
				Key:     k,
				Value:   v,
				Reason:  "no v1.1 mapping",
			})
		}
	}
}

// topLevelKey returns the top-level mapping key a rendered block
// introduces (e.g. "pg_connection" for "pg_connection: postgres://…",
// "retention" for a "retention:\n  keep_for: …" block).  It scans for
// the first non-comment, non-indented "key:" line so blocks whose first
// line is a comment (e.g. "# backup_method: postgres …") don't count as
// introducing a key.  Returns "" when the block emits no top-level key
// (pure comment blocks), which the caller treats as "always emit".
func topLevelKey(rendered string) string {
	for _, line := range strings.Split(rendered, "\n") {
		if line == "" {
			continue
		}
		// Nested / indented lines belong to a block already counted by
		// its header line; skip them.
		if line[0] == ' ' || line[0] == '\t' {
			continue
		}
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		if i := strings.Index(trimmed, ":"); i > 0 {
			return trimmed[:i]
		}
	}
	return ""
}

// yamlString quotes a YAML string only if it would otherwise be
// ambiguous.  We keep it tight: alphanumerics + dash + underscore
// are bare; everything else is double-quoted with backslash escapes.
func yamlString(s string) string {
	if s == "" {
		return `""`
	}
	bare := true
	for _, ch := range s {
		switch {
		case ch >= 'a' && ch <= 'z':
		case ch >= 'A' && ch <= 'Z':
		case ch >= '0' && ch <= '9':
		case ch == '-' || ch == '_' || ch == '.' || ch == '/':
		default:
			bare = false
		}
	}
	if bare {
		return s
	}
	return `"` + strings.ReplaceAll(strings.ReplaceAll(s, `\`, `\\`), `"`, `\"`) + `"`
}
