package restore_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/cybertec-postgresql/pg_hardstorage/internal/restore"
)

// inheritedAutoConf is what a backup of a previously-restored (and
// since promoted) cluster carries in postgresql.auto.conf: the
// auto-recovery primer an earlier restore appended (legacy shape, no
// end marker), an earlier PITR block, postverify's own appends, and a
// target that survived an ALTER SYSTEM rewrite (which strips comments,
// so no marker at all).
const inheritedAutoConf = "# Do not edit this file manually!\n" +
	"# It will be overwritten by the ALTER SYSTEM command.\n" +
	"listen_addresses = '*'\n" +
	"\n# --- pg_hardstorage managed block (auto-recovery) ---\n" +
	"recovery_target = 'immediate'\n" +
	"recovery_target_action = 'promote'\n" +
	"restore_command = 'old-fetch %f %p'\n" +
	"\n# pg_hardstorage postverify (auto-appended):\n" +
	"recovery_target = 'immediate'\n" +
	"recovery_target_action = 'promote'\n" +
	"\n# --- pg_hardstorage managed block (PITR) ---\n" +
	"restore_command = 'old-fetch %f %p'\n" +
	"recovery_target_time = '2025-01-01 00:00:00+00'\n" +
	"recovery_target_inclusive = true\n" +
	"recovery_target_action = 'pause'\n" +
	"recovery_target_timeline = 'latest'\n" +
	"# --- end pg_hardstorage managed block ---\n" +
	"recovery_target_xid = '4242'\n" +
	"work_mem = '8MB'\n"

// effectiveGUCs applies PostgreSQL's config-file rule (the LAST
// occurrence of a name wins) and returns the surviving values.
func effectiveGUCs(t *testing.T, body string) map[string]string {
	t.Helper()
	out := map[string]string{}
	for _, ln := range strings.Split(body, "\n") {
		ln = strings.TrimSpace(ln)
		if ln == "" || strings.HasPrefix(ln, "#") {
			continue
		}
		k, v, ok := strings.Cut(ln, "=")
		if !ok {
			t.Fatalf("unparseable auto.conf line %q", ln)
		}
		out[strings.TrimSpace(k)] = strings.Trim(strings.TrimSpace(v), "'")
	}
	return out
}

// activeTargets lists the recovery_target* GUCs that end up non-empty;
// PostgreSQL FATALs ("multiple recovery targets specified") on >1.
func activeTargets(g map[string]string) []string {
	var got []string
	for _, k := range []string{"recovery_target", "recovery_target_lsn", "recovery_target_time", "recovery_target_name", "recovery_target_xid"} {
		if g[k] != "" {
			got = append(got, k)
		}
	}
	return got
}

func writeInherited(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "postgresql.auto.conf"), []byte(inheritedAutoConf), 0o600); err != nil {
		t.Fatal(err)
	}
	return dir
}

func readAutoConf(t *testing.T, dir string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(dir, "postgresql.auto.conf"))
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

// Regression (H45): recovery settings inherited from an earlier
// restore must not leak into a new one. Before the fix the new block
// was appended after them, so `restore --to <time>` on such a backup
// FATALed with "multiple recovery targets", and --to-latest / standby
// silently stopped at the backup's consistency point.
func TestWriteRecoveryFiles_NeutralisesInheritedTargets(t *testing.T) {
	cases := []struct {
		name string
		r    restore.Recovery
		want []string // the only recovery targets that may be active
	}{
		{"to-time", restore.Recovery{Enable: true, RestoreCommand: "new %f %p",
			TargetTime: time.Date(2026, 5, 1, 12, 0, 0, 0, time.UTC), Inclusive: true}, []string{"recovery_target_time"}},
		{"to-lsn", restore.Recovery{Enable: true, RestoreCommand: "new %f %p", TargetLSN: "0/5000000", Inclusive: true}, []string{"recovery_target_lsn"}},
		{"to-latest", restore.Recovery{Enable: true, RestoreCommand: "new %f %p", Action: "promote"}, nil},
		{"standby", restore.Recovery{Enable: true, RestoreCommand: "new %f %p", StandbyMode: true}, nil},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := writeInherited(t)
			if err := restore.WriteRecoveryFiles(dir, tc.r); err != nil {
				t.Fatal(err)
			}
			body := readAutoConf(t, dir)
			g := effectiveGUCs(t, body)
			if got := activeTargets(g); strings.Join(got, ",") != strings.Join(tc.want, ",") {
				t.Errorf("active recovery targets = %v, want %v\n%s", got, tc.want, body)
			}
			if g["restore_command"] != "new %f %p" {
				t.Errorf("restore_command = %q, want the new one", g["restore_command"])
			}
			if strings.Contains(body, "old-fetch") || strings.Contains(body, "postverify") {
				t.Errorf("previous pg_hardstorage blocks were not stripped:\n%s", body)
			}
			if n := strings.Count(body, "pg_hardstorage managed block ("); n != 1 {
				t.Errorf("want exactly one managed block, got %d:\n%s", n, body)
			}
			// Operator settings outside our blocks survive.
			if g["listen_addresses"] != "*" || g["work_mem"] != "8MB" {
				t.Errorf("operator settings lost:\n%s", body)
			}
		})
	}
}

// Same guarantee for the plain-restore primer.
func TestWriteAutoRecovery_NeutralisesInheritedTargets(t *testing.T) {
	dir := writeInherited(t)
	if err := restore.WriteAutoRecovery(dir, "db1", "file:///r", ""); err != nil {
		t.Fatal(err)
	}
	body := readAutoConf(t, dir)
	g := effectiveGUCs(t, body)
	if got := activeTargets(g); len(got) != 1 || got[0] != "recovery_target" || g["recovery_target"] != "immediate" {
		t.Errorf("active recovery targets = %v (recovery_target=%q), want only recovery_target='immediate'\n%s",
			got, g["recovery_target"], body)
	}
	if strings.Contains(body, "old-fetch") {
		t.Errorf("previous blocks not stripped:\n%s", body)
	}
	if n := strings.Count(body, "pg_hardstorage managed block ("); n != 1 {
		t.Errorf("want exactly one managed block, got %d:\n%s", n, body)
	}
	// Re-running the primer (e.g. a retried restore) must not stack.
	if err := restore.WriteAutoRecovery(dir, "db1", "file:///r", ""); err != nil {
		t.Fatal(err)
	}
	if n := strings.Count(readAutoConf(t, dir), "pg_hardstorage managed block ("); n != 1 {
		t.Errorf("re-run stacked blocks: %d", n)
	}
}
