package cli_test

import (
	"bytes"
	"strings"
	"testing"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/cybertec-postgresql/pg_hardstorage/internal/cli"
)

// productCommands returns every command in the live root tree,
// excluding cobra's auto-generated `help` and `completion`
// machinery — their metadata is cobra's, not the project's, and
// the cmdtree walker skips them for the same reason.
func productCommands(root *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	var rec func(*cobra.Command)
	rec = func(c *cobra.Command) {
		out = append(out, c)
		for _, sub := range c.Commands() {
			if sub.Name() == "help" || sub.Name() == "completion" {
				continue
			}
			rec(sub)
		}
	}
	rec(root)
	return out
}

// TestCLICompleteness_CommandMetadata asserts that every command
// carries a one-line description and that every flag carries a
// non-empty usage string.
//
// This is a docs-drift guard, not a behavioural test: the website
// CLI reference and the man pages are generated by cmd/docsgen
// straight from these fields, so an empty Short or an empty flag
// Usage renders as a blank hole in the published documentation.
// Adding a command or flag without describing it fails CI here.
func TestCLICompleteness_CommandMetadata(t *testing.T) {
	root := cli.NewRoot()
	cmds := productCommands(root)
	if len(cmds) < 50 {
		t.Fatalf("expected the full command surface (50+ commands); got %d", len(cmds))
	}

	for _, c := range cmds {
		path := c.CommandPath()

		// Every command needs a one-line summary. The root is
		// allowed a long description only, so skip it here.
		if c != root && strings.TrimSpace(c.Short) == "" {
			t.Errorf("%s: empty Short — it would render blank in the CLI reference", path)
		}

		// Every flag declared on this command needs a usage string.
		// LocalFlags() is each command's own (non-inherited) set, so
		// every flag is checked exactly once at its definition site.
		c.LocalFlags().VisitAll(func(f *pflag.Flag) {
			if strings.TrimSpace(f.Usage) == "" {
				t.Errorf("%s: flag --%s has an empty usage string", path, f.Name)
			}
		})
	}
}

// TestCLICompleteness_HelpRenders asserts that `--help` renders
// for every command without erroring or panicking, and produces
// non-empty output. A broken help template or a nil dereference
// in a custom help/usage function is caught here for the whole
// command surface at once.
func TestCLICompleteness_HelpRenders(t *testing.T) {
	root := cli.NewRoot()
	var buf bytes.Buffer
	root.SetOut(&buf)
	root.SetErr(&buf)

	for _, c := range productCommands(root) {
		c := c
		func() {
			defer func() {
				if r := recover(); r != nil {
					t.Errorf("%s: --help panicked: %v", c.CommandPath(), r)
				}
			}()
			buf.Reset()
			if err := c.Help(); err != nil {
				t.Errorf("%s: --help returned an error: %v", c.CommandPath(), err)
			}
			if buf.Len() == 0 {
				t.Errorf("%s: --help rendered nothing", c.CommandPath())
			}
		}()
	}
}
