package main

import (
	"bytes"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"testing"
)

// The generated CLI reference, man pages and shell completions must match
// the command tree. The CLI index says "CI fails on drift", but nothing
// checked it locally: several commands' man pages (llm doctor, jit,
// dsa locate, audit verify-bundle, …) were left describing flags and
// exit codes that had changed. Regenerate with `make docs-regen`.
func TestGeneratedDocsAreFresh(t *testing.T) {
	root := filepath.Join("..", "..")
	tmp := t.TempDir()
	gen := map[string]string{
		"cli":         filepath.Join(tmp, "cli"),
		"man":         filepath.Join(tmp, "man"),
		"completions": filepath.Join(tmp, "completions"),
	}
	if err := run("all", gen["cli"], gen["man"], gen["completions"]); err != nil {
		t.Fatal(err)
	}
	committed := map[string]string{
		"cli":         filepath.Join(root, "docs", "reference", "cli"),
		"man":         filepath.Join(root, "man", "man1"),
		"completions": filepath.Join(root, "completions"),
	}
	for kind, genDir := range gen {
		want := readTree(t, genDir)
		have := readTree(t, committed[kind])
		for name, body := range want {
			got, ok := have[name]
			if !ok {
				t.Errorf("%s: %s is missing — run `make docs-regen`", kind, name)
				continue
			}
			if !bytes.Equal(got, body) {
				t.Errorf("%s: %s is stale — run `make docs-regen`", kind, name)
			}
		}
		// A generated page for a command that no longer exists.
		for name, body := range have {
			if _, ok := want[name]; ok {
				continue
			}
			if path.Base(name) == "README.md" ||
				(kind == "cli" && !bytes.Contains(body, []byte("AUTO-GENERATED by cmd/docsgen"))) {
				continue // hand-written file living next to the generated ones
			}
			t.Errorf("%s: %s has no command any more — run `make docs-regen` and delete it", kind, name)
		}
	}
}

func readTree(t *testing.T, dir string) map[string][]byte {
	t.Helper()
	out := map[string][]byte{}
	err := filepath.WalkDir(dir, func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		rel, _ := filepath.Rel(dir, p)
		b, rerr := os.ReadFile(p)
		if rerr != nil {
			return rerr
		}
		out[filepath.ToSlash(rel)] = b
		return nil
	})
	if err != nil {
		t.Fatalf("read %s: %v", dir, err)
	}
	return out
}
