// docsgen is the documentation generator that emits
// machine-comparable reference pages from the canonical
// source of truth.
//
// Today it produces:
//
//   - docs/reference/cli/*.md  — one per Cobra subcommand,
//     via cobra/doc.GenMarkdownTree
//   - man/man1/pg_hardstorage*.1 — manpages, via
//     cobra/doc.GenManTree
//
// Future generators (config schema, manifest schema, audit
// events, metric catalogue, …) land here; each is a new
// subcommand.  See docs/DOC_PLAN.md "Auto-generation map".
//
// The CI gate `make docs-regen` runs every generator and
// `git diff --exit-code` afterwards; drift between source
// of truth and committed docs fails the build.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"github.com/cybertec-postgresql/pg_hardstorage/internal/cli"
)

func main() {
	target := flag.String("target", "all", "what to generate: cli | man | completions | all")
	cliDir := flag.String("cli-dir", "docs/reference/cli", "output dir for CLI markdown")
	manDir := flag.String("man-dir", "man/man1", "output dir for manpages")
	completionsDir := flag.String("completions-dir", "completions", "output dir for shell completions (bash/zsh/fish subdirs)")
	flag.Parse()

	if err := run(*target, *cliDir, *manDir, *completionsDir); err != nil {
		log.Fatalf("docsgen: %v", err)
	}
}

func run(target, cliDir, manDir, completionsDir string) error {
	root := cli.NewRoot()
	// Make the rendered command tree deterministic — the
	// generator must produce byte-identical output across
	// runs so the CI diff gate is meaningful.
	root.DisableAutoGenTag = true

	switch target {
	case "cli":
		return genCLI(root, cliDir)
	case "man":
		return genMan(root, manDir)
	case "completions":
		return genCompletions(root, completionsDir)
	case "all":
		if err := genCLI(root, cliDir); err != nil {
			return err
		}
		if err := genMan(root, manDir); err != nil {
			return err
		}
		return genCompletions(root, completionsDir)
	default:
		return fmt.Errorf("unknown -target=%q (want cli | man | completions | all)", target)
	}
}

// genCLI emits one Markdown page per (sub-)command into
// cliDir.  The Cobra default generator produces files like
// `pg_hardstorage_init.md`; we add a YAML front-matter +
// auto-gen banner so MkDocs picks the page up cleanly.
func genCLI(root *cobra.Command, dir string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	// linkHandler keeps the cross-links between command
	// pages relative — no absolute URLs that would break
	// when the site moves to a domain.
	linkHandler := func(name string) string { return name }
	// filePrepender injects the YAML front-matter every
	// MkDocs Material page expects + the do-not-edit
	// banner that prevents accidental hand edits.
	filePrepender := func(filename string) string {
		base := filepath.Base(filename)
		// Cobra writes "pg_hardstorage_init.md" → display
		// title "pg_hardstorage init".
		title := strings.TrimSuffix(base, ".md")
		title = strings.ReplaceAll(title, "_", " ")
		return "---\n" +
			"title: \"" + title + "\"\n" +
			"description: CLI reference for the " + title + " command.\n" +
			"tags:\n" +
			"  - cli\n" +
			"  - reference\n" +
			"---\n\n" +
			"<!-- AUTO-GENERATED by cmd/docsgen — do not edit.  Run\n" +
			"     `make docs-regen` after changing the Cobra command\n" +
			"     definitions to refresh this page. -->\n\n"
	}
	if err := doc.GenMarkdownTreeCustom(root, dir, filePrepender, linkHandler); err != nil {
		return fmt.Errorf("GenMarkdownTreeCustom: %w", err)
	}
	// Add a stable index page so MkDocs nav references
	// `reference/cli/index.md`.
	if err := writeCLIIndex(root, dir); err != nil {
		return err
	}
	return nil
}

// writeCLIIndex emits an alphabetised index of every
// generated CLI page.  Lets MkDocs render a navigable
// "CLI reference" landing page.
func writeCLIIndex(root *cobra.Command, dir string) error {
	var cmds []*cobra.Command
	collect(root, &cmds)
	// Sort by Path() so the rendered list is alphabetical.
	for i := 0; i < len(cmds); i++ {
		for j := i + 1; j < len(cmds); j++ {
			if cmds[i].CommandPath() > cmds[j].CommandPath() {
				cmds[i], cmds[j] = cmds[j], cmds[i]
			}
		}
	}

	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("title: CLI reference\n")
	b.WriteString("description: One page per pg_hardstorage subcommand, auto-generated from the Cobra command tree.\n")
	b.WriteString("tags:\n")
	b.WriteString("  - cli\n")
	b.WriteString("  - reference\n")
	b.WriteString("---\n\n")
	b.WriteString("<!-- AUTO-GENERATED by cmd/docsgen — do not edit. -->\n\n")
	b.WriteString("# CLI reference\n\n")
	b.WriteString("One page per `pg_hardstorage` subcommand.  Pages are\n")
	b.WriteString("generated from the Cobra command tree on every\n")
	b.WriteString("`make docs-regen`; CI fails on drift.\n\n")
	b.WriteString("| Command | Synopsis |\n")
	b.WriteString("| --- | --- |\n")
	for _, c := range cmds {
		if c.Hidden || c.Name() == "help" {
			continue
		}
		path := c.CommandPath()
		filename := strings.ReplaceAll(path, " ", "_") + ".md"
		short := strings.ReplaceAll(c.Short, "|", "\\|")
		fmt.Fprintf(&b, "| [`%s`](%s) | %s |\n", path, filename, short)
	}
	out := filepath.Join(dir, "index.md")
	return os.WriteFile(out, []byte(b.String()), 0o644)
}

// collect walks the Cobra tree DF, accumulating commands.
func collect(c *cobra.Command, out *[]*cobra.Command) {
	*out = append(*out, c)
	for _, child := range c.Commands() {
		collect(child, out)
	}
}

// genMan emits one manpage per top-level command + the
// root.  Compressed during package build (debian/rules
// handles that); we ship the uncompressed source.
func genMan(root *cobra.Command, dir string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	header := &doc.GenManHeader{
		Title:   "PG_HARDSTORAGE",
		Section: "1",
		// Pin the date so reproducible builds stay
		// reproducible.  Update by-hand on a release; the
		// docs-regen gate will catch a stale value.
		Date:   pinnedDate(),
		Source: "pg_hardstorage Manual",
		Manual: "pg_hardstorage Manual",
	}
	return doc.GenManTree(root, header, dir)
}

// pinnedDate is the manpage Date field.  Pinned to a
// constant so reproducible builds bit-match.  Updated
// per-release as part of the release-prep checklist.
func pinnedDate() *time.Time {
	t, _ := time.Parse("2006-01-02", "2026-05-04")
	return &t
}

// genCompletions emits bash / zsh / fish completion
// scripts.  Both Debian and RPM packaging install these
// from `completions/<shell>/` into the standard system
// paths; the generator is the single source of truth so
// the committed scripts match the live Cobra command tree.
//
// Output paths:
//
//	completions/bash/pg_hardstorage
//	completions/zsh/_pg_hardstorage
//	completions/fish/pg_hardstorage.fish
//
// `make docs-regen` rebuilds these alongside the CLI
// markdown reference and manpages; CI fails on drift.
func genCompletions(root *cobra.Command, dir string) error {
	for _, sub := range []string{"bash", "zsh", "fish"} {
		if err := os.MkdirAll(filepath.Join(dir, sub), 0o755); err != nil {
			return err
		}
	}
	// Cobra's GenBashCompletionFile produces the bash-
	// completion v2 form by default in cobra v1.8 — what
	// modern shells expect.
	bashPath := filepath.Join(dir, "bash", "pg_hardstorage")
	if err := root.GenBashCompletionFileV2(bashPath, true); err != nil {
		return fmt.Errorf("genCompletions bash: %w", err)
	}
	// Zsh completion file convention: `_<name>` under
	// fpath / `vendor-completions/`.
	zshPath := filepath.Join(dir, "zsh", "_pg_hardstorage")
	if err := root.GenZshCompletionFile(zshPath); err != nil {
		return fmt.Errorf("genCompletions zsh: %w", err)
	}
	// Fish completions go under `vendor_completions.d/<name>.fish`.
	fishPath := filepath.Join(dir, "fish", "pg_hardstorage.fish")
	if err := root.GenFishCompletionFile(fishPath, true); err != nil {
		return fmt.Errorf("genCompletions fish: %w", err)
	}
	return nil
}
