// Package compose generates a docker-compose YAML from a
// testkit fleet.  Every fleet entry expands to one or more
// service stanzas (PG container, optional Toxiproxy front
// door); the fleet's count + Patroni-nodes determine
// container multiplicity.
//
// The generated YAML is deterministic — identical fleet +
// identical options produce identical bytes.  The output
// includes a comment header noting the generation provenance
// so operators reading docker-compose ps know what produced it.
package compose

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/cybertec-postgresql/pg_hardstorage/internal/testkit/catalog"
	"github.com/cybertec-postgresql/pg_hardstorage/internal/testkit/config"
	"github.com/cybertec-postgresql/pg_hardstorage/internal/testkit/imagetag"
)

// Options drives compose generation.
type Options struct {
	// ProjectName is the docker-compose project name.
	// Defaults to "pgvalidate" if empty.
	ProjectName string

	// ImageRepo is the testbed image registry repo prefix
	// (matches the value used by `image build`).  Defaults
	// to ghcr.io/cybertec-postgresql/pg-hardstorage-testbed.
	ImageRepo string

	// HostPortBase is the first host port allocated to the
	// first PG cell; subsequent cells get +1 each.
	// Default 15432.
	HostPortBase int

	// IncludeToxiproxy: emit one toxiproxy container per
	// cell so the fault catalogue's `toxiproxy(...)` action
	// has something to talk to.  On by default.
	IncludeToxiproxy bool

	// IncludeRepoVolume: emit a host-bind-mount volume
	// shared across all cells for the file://-mode repo.
	// On by default.  Disable when the soak run uses an
	// external S3.
	IncludeRepoVolume bool

	// HostRepoDir is the host path bind-mounted into every
	// container as /var/lib/pg_hardstorage/repo.  Default
	// "./repo-data" — relative to where docker compose is
	// invoked.
	HostRepoDir string

	// DockerfileDir is the directory holding the testbed
	// Dockerfiles + entrypoint-pg.sh.  The generator reads
	// these at runtime to compute imagetag.RecipeDigest so
	// the image tag carries the recipe content fingerprint —
	// any change to the entrypoint or Dockerfile produces a
	// different tag, which forces a rebuild instead of
	// silently reusing a stale local image.
	//
	// Default "dockerfiles/testbed" (relative to cwd, which
	// run_testing.sh sets to the repo root).  Empty / unreadable
	// path → falls back to the legacy unversioned tag.
	DockerfileDir string
}

// Generate emits a docker-compose YAML for fleet.  The catalog
// is consulted to translate every (OS, PG, arch) into a real
// image tag matching the `image build` driver's tag scheme.
func Generate(fleet *config.Fleet, c *catalog.Catalog, opts Options) (string, error) {
	if fleet == nil || len(fleet.Entries) == 0 {
		return "", fmt.Errorf("compose: fleet is empty")
	}
	defaults(&opts)

	var b strings.Builder
	fmt.Fprintf(&b,
		"# Generated by pg_hardstorage_testkit compose generate.\n# Project: %s | Cells: %d\n# Edits will be overwritten on regeneration.\n\n",
		opts.ProjectName, len(fleet.Entries))
	fmt.Fprintln(&b, "name: "+opts.ProjectName)
	fmt.Fprintln(&b, "")
	fmt.Fprintln(&b, "services:")

	// Use the shared port allocator so `validate` and other
	// callers can re-derive the same map without parsing the
	// generated YAML.
	ports := AllocatePorts(fleet, opts.HostPortBase)

	// Sort entries by name so output is stable.
	sorted := append([]config.FleetEntry{}, fleet.Entries...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	for _, e := range sorted {
		o, err := c.FindOS(e.OS)
		if err != nil {
			return "", err
		}
		image := imageTagFor(opts.ImageRepo, e, c, opts.DockerfileDir)
		units := e.Count
		nodesPerUnit := 1
		if e.EffectiveRole() == "patroni-cluster" {
			nodesPerUnit = e.Nodes
		}
		for unit := 0; unit < units; unit++ {
			for node := 0; node < nodesPerUnit; node++ {
				name := containerName(e, unit, node, nodesPerUnit)
				port := ports[name]
				if err := writePGService(&b, name, image, e, o, port, opts); err != nil {
					return "", err
				}
				if opts.IncludeToxiproxy {
					writeToxiproxyService(&b, name, opts.ProjectName)
				}
			}
		}
	}

	// The repo mount is now emitted per-service as a long-form
	// `type: bind` mount (see writePGService).  The earlier
	// "named volume with driver_opts: o=bind" indirection plus
	// the short-form `:z` mount option triggered the warning
	//
	//   WARN[0000] mount of type `volume` should not define `bind` option
	//
	// because Docker Compose expands the short-form `:z` into a
	// `bind:` sub-block, which is only valid on `type: bind`
	// mounts (not `type: volume`).  Going straight to a long-form
	// bind mount eliminates the warning and removes the
	// top-level `volumes:` block entirely.

	fmt.Fprintln(&b, "")
	fmt.Fprintln(&b, "networks:")
	fmt.Fprintln(&b, "  default:")
	fmt.Fprintln(&b, "    name: "+opts.ProjectName+"-net")

	return b.String(), nil
}

func defaults(o *Options) {
	if o.ProjectName == "" {
		o.ProjectName = "pgvalidate"
	}
	if o.ImageRepo == "" {
		o.ImageRepo = "ghcr.io/cybertec-postgresql/pg-hardstorage-testbed"
	}
	if o.HostPortBase == 0 {
		o.HostPortBase = 15432
	}
	if o.HostRepoDir == "" {
		o.HostRepoDir = "./repo-data"
	}
	if o.DockerfileDir == "" {
		o.DockerfileDir = "dockerfiles/testbed"
	}
	// Booleans default to true via explicit Generate-time
	// inversion: compose users get the safe defaults unless
	// they actively turn things off.  The flag-binding code
	// in the testkit CLI sets these explicitly via
	// `cmd.Flags().BoolVar(..., true, ...)` so the
	// downstream view here is "what the operator chose".
}

// containerName builds a deterministic container name.  Patroni
// nodes get a "-nodeN" suffix; everything else gets "-cN" for
// the unit index when count > 1.
func containerName(e config.FleetEntry, unit, node, nodesPerUnit int) string {
	if nodesPerUnit > 1 {
		return fmt.Sprintf("%s-c%d-node%d", e.Name, unit, node)
	}
	if e.Count > 1 {
		return fmt.Sprintf("%s-c%d", e.Name, unit)
	}
	return e.Name
}

// imageTagFor returns the testbed image tag matching the one
// the image-build driver would have emitted — delegates to
// internal/testkit/imagetag so the two stay in lock-step.
//
// Recipe digest is per-family because each family has its own
// Dockerfile.  The digest is "" when dockerfileDir is unset or
// unreadable — the legacy unversioned tag still works for
// stand-alone tests that bypass the on-disk recipe.
func imageTagFor(repo string, e config.FleetEntry, c *catalog.Catalog, dockerfileDir string) string {
	o, _ := c.FindOS(e.OS)
	pkg := c.EffectivePackages(o)
	recipe := imagetag.RecipeDigest(o.Family, dockerfileDir)
	return imagetag.ForWithRecipe(repo, e.OS, e.PG, e.EffectiveArch(), o.Family, pkg, recipe)
}

// writePGService emits one PG-service stanza.  The container
// gets the testbed image, a host-mapped 5432 port, and (when
// fault injection needs it) the CAP_NET_ADMIN capability so
// network_block can run iptables.
//
// `container_name` is project-prefixed (`<project>-<name>`) so
// two simultaneous runs — or a re-run after a previous failure
// left orphaned containers — cannot collide on the global
// docker name namespace.  The `services:` map key stays
// unprefixed because compose scopes services per-project on
// its own.
func writePGService(b *strings.Builder, name, image string, e config.FleetEntry, o *catalog.OS, port int, opts Options) error {
	fmt.Fprintf(b, "  %s:\n", name)
	fmt.Fprintf(b, "    image: %s\n", image)
	fmt.Fprintf(b, "    container_name: %s\n", PrefixedContainerName(opts.ProjectName, name))
	// pull_policy: missing — try the local image first;
	// fall back to a registry pull only if absent.  Soak
	// runs build the testbed images locally via
	// `pg_hardstorage_testkit image build`, and the registry
	// (ghcr.io/cybertec-postgresql/pg-hardstorage-testbed)
	// is private until the project ships a public image set.
	// Without this, compose tries to pull missing-from-public
	// images and fails with a `denied` error before the
	// local layers ever get a chance.
	fmt.Fprintln(b, "    pull_policy: missing")
	// `restart: unless-stopped` is load-bearing for the soak's
	// fault-injection contract.  A `pg_kill_9` fault sends
	// SIGKILL to the testbed container's pg_hardstorage agent
	// (PID 1 inside the cell), which exits the container.
	// Without an explicit restart policy compose leaves it
	// Exited(137) forever, every subsequent fault_apply hits
	// "container is not running", every verify_failed against
	// that cell records as a wedge, and the soak's recovery
	// metric stops measuring anything real.  With
	// `unless-stopped`, docker re-starts the container on its
	// own and the orchestrator's heal_window logic gets a
	// chance to observe actual recovery.  `unless-stopped`
	// (vs `always`) so an operator's `docker stop` during
	// post-mortem isn't undone by the daemon.
	fmt.Fprintln(b, "    restart: unless-stopped")
	// `init: true` makes Docker run the container under a real
	// reaping init (docker-init / tini) as PID 1.  The testbed
	// entrypoint ends with `exec tail -F`, which is NOT a
	// reaping init: when the `cgroup_squeeze` fault OOM-kills
	// PostgreSQL's postmaster, its orphaned backends are
	// re-parented to PID 1, and once they exit a non-reaping
	// PID 1 leaves them as zombies forever.  A zombie keeps its
	// PID allocated, so the recycled-PID it pins can make a
	// fresh postmaster refuse to start ("lock file ... already
	// exists"); zombies also accumulate across a long soak and
	// pressure the container's PID space.  docker-init reaps
	// them.  Signal semantics are unchanged: `docker kill -s N`
	// still targets PID 1, so the `signal` fault's
	// container-exit-then-Start contract holds as before.
	fmt.Fprintln(b, "    init: true")
	fmt.Fprintln(b, "    cap_add:")
	fmt.Fprintln(b, "      - NET_ADMIN     # iptables fault primitives")
	fmt.Fprintln(b, "      - SYS_NICE      # cgroup_squeeze fault primitive")
	// SYS_RESOURCE lets fd_exhaustion lower another process's
	// RLIMIT_NOFILE via prlimit(2).  Docker's default capability
	// set omits it, so without this every fd_exhaustion attempt
	// failed with "target lacks CAP_SYS_RESOURCE" (the soak hit
	// this ~200 times in a single 8h run, never once firing the
	// fault).  See fdExhaustionFault in internal/testkit/inject.
	fmt.Fprintln(b, "      - SYS_RESOURCE  # fd_exhaustion (prlimit) fault primitive")
	fmt.Fprintln(b, "    environment:")
	fmt.Fprintf(b, "      - PG_VERSION=%s\n", e.PG)
	fmt.Fprintf(b, "      - PGUSER=postgres\n")
	fmt.Fprintf(b, "      - HSDEPLOYMENT=%s\n", e.Name)
	// SECURITY: bind the host port to 127.0.0.1, NOT 0.0.0.0.
	// The testbed entrypoint configures `host all all 0.0.0.0/0
	// trust` in pg_hba.conf (it has to — the agent connects from
	// the docker bridge gateway IP, not 127.0.0.1/32 inside the
	// container's namespace), and combined with `0.0.0.0:NNNN`
	// binding that exposes a no-auth PG on every interface the
	// host has.  On a LAN-reachable box this is exactly the
	// "exposed PG with trust auth" footgun that lets an attacker
	// run `COPY ... FROM PROGRAM 'curl … | sh'` and land a
	// cryptominer at `/tmp/mysql` running as the postgres user
	// inside the container — observed in soak testing within
	// minutes of the first port bind.  Restricting the host bind
	// to 127.0.0.1 means only the box's own loopback can reach
	// the port, and the docker bridge → PG path inside the
	// container is unchanged.
	fmt.Fprintln(b, "    ports:")
	fmt.Fprintf(b, "      - %q\n", fmt.Sprintf("127.0.0.1:%d:5432", port))
	if opts.IncludeRepoVolume {
		// Long-form `type: bind` mount, one per service, with
		// the absolute host path resolved up front.  Docker
		// daemon resolves bind paths against ITS OWN cwd
		// (typically `/`), not the caller's, so a relative
		// HostRepoDir lands at the wrong place at the daemon
		// and the mount fails with "no such file or directory".
		// filepath.Abs is from the caller's cwd, which is what
		// the operator means.
		//
		// `bind: { selinux: z }` is the long-form spelling of
		// the short-form `:z` flag — required for Fedora /
		// RHEL / CentOS hosts (SELinux enforcing by default)
		// so container_t can write through to the host dir
		// (without the relabel `repo init` fails with
		// `HSREPO: permission denied` despite uid 0 in the
		// container — DAC says yes, MAC says no).  Lowercase
		// `z` (NOT `Z`) so the SELinux label is SHARED across
		// cells, which all write to the same repo concurrently;
		// `Z` would isolate the label per-container and break
		// concurrent shared-repo writes.  No-op on Debian /
		// SUSE / macOS / Windows runtimes that don't enforce
		// SELinux.
		//
		// The earlier short-form `repo-data:/path:z` plus a
		// top-level `volumes: repo-data: driver_opts: o=bind`
		// indirection triggered a Compose warning
		//
		//   WARN[0000] mount of type `volume` should not
		//                define `bind` option
		//
		// because Compose expands `:z` into a `bind:` sub-block
		// that's only valid on `type: bind` mounts.  The long
		// form here puts everything in the right slot.
		dev, err := filepath.Abs(opts.HostRepoDir)
		if err != nil {
			return fmt.Errorf("compose: resolve HostRepoDir: %w", err)
		}
		fmt.Fprintln(b, "    volumes:")
		fmt.Fprintln(b, "      - type: bind")
		fmt.Fprintf(b, "        source: %s\n", dev)
		fmt.Fprintln(b, "        target: /var/lib/pg_hardstorage/repo")
		fmt.Fprintln(b, "        bind:")
		fmt.Fprintln(b, "          selinux: z")
	}
	fmt.Fprintln(b, "    labels:")
	fmt.Fprintf(b, "      pg_hardstorage_testkit.role: pg\n")
	fmt.Fprintf(b, "      pg_hardstorage_testkit.os: %q\n", e.OS)
	fmt.Fprintf(b, "      pg_hardstorage_testkit.pg: %q\n", e.PG)
	fmt.Fprintf(b, "      pg_hardstorage_testkit.arch: %q\n", e.EffectiveArch())
	fmt.Fprintf(b, "      pg_hardstorage_testkit.deployment: %q\n", e.Name)
	if e.Filesystem != "" {
		fmt.Fprintf(b, "      pg_hardstorage_testkit.fs: %q\n", e.Filesystem)
	}
	// Quietly silence unused-arg if a future refactor drops
	// the os arg.
	_ = o
	return nil
}

// writeToxiproxyService emits a toxiproxy front door for the
// PG container.  Used by the `toxiproxy(...)` fault primitive
// to inject latency / 503 storms.
//
// `container_name` is project-prefixed for the same reason
// writePGService prefixes (avoid cross-run collisions).  The
// `peer` label carries the project-prefixed PG container_name
// so anyone querying `docker ps -f label=...peer=X` to find
// the paired PG cell gets a name they can pass directly to
// `docker exec`.
func writeToxiproxyService(b *strings.Builder, peer, project string) {
	serviceName := peer + "-tox"
	pgContainer := PrefixedContainerName(project, peer)
	toxContainer := PrefixedContainerName(project, serviceName)
	fmt.Fprintf(b, "  %s:\n", serviceName)
	fmt.Fprintln(b, "    image: ghcr.io/shopify/toxiproxy:2.5.0")
	fmt.Fprintf(b, "    container_name: %s\n", toxContainer)
	fmt.Fprintln(b, "    labels:")
	fmt.Fprintln(b, "      pg_hardstorage_testkit.role: toxiproxy")
	fmt.Fprintf(b, "      pg_hardstorage_testkit.peer: %q\n", pgContainer)
}
