// Package translate converts a WAL-G env file into a
// pg_hardstorage.yaml configuration.
//
// WAL-G is configured via environment variables — typically
// sourced from /etc/default/wal-g, /etc/wal-g/walg.env, or a
// systemd EnvironmentFile drop-in.  This package parses any
// shell-like KEY=VALUE file (one assignment per line, optional
// `export ` prefix, comments with `#`) and emits a YAML
// document matching the conventions of the pgBackRest / Barman
// translators.
//
// The mapping is intentionally lossy: WAL-G knobs that have a
// direct semantic equivalent are translated; encryption envelopes
// (libsodium, GPG, PGP) become refusal-comments because they're
// not byte-compatible with our envelope.
package translate

import (
	"bufio"
	"fmt"
	"io"
	"net/url"
	"sort"
	"strings"
)

// EnvFile is the parsed env-file representation.  Keys appear in
// insertion order so emission is stable across Translate runs.
type EnvFile struct {
	KV    map[string]string
	Order []string
}

// Parse reads a WAL-G env-style file: one KEY=VALUE assignment per
// non-blank, non-comment line, optional `export ` prefix, optional
// quoting around the value.
func Parse(r io.Reader) (*EnvFile, error) {
	out := &EnvFile{KV: map[string]string{}}
	scanner := bufio.NewScanner(r)
	scanner.Buffer(make([]byte, 64*1024), 1024*1024)
	lineno := 0
	for scanner.Scan() {
		lineno++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// Strip an optional `export ` prefix.
		line = strings.TrimPrefix(line, "export ")
		eq := strings.Index(line, "=")
		if eq < 0 {
			return nil, fmt.Errorf("line %d: missing '=' in %q", lineno, line)
		}
		key := strings.TrimSpace(line[:eq])
		val := strings.TrimSpace(line[eq+1:])
		// Strip end-of-line comment after the value (only when
		// preceded by whitespace, so `#foo` inside a quoted
		// value survives).
		for _, sep := range []string{" #", "\t#"} {
			if i := strings.Index(val, sep); i >= 0 {
				val = strings.TrimSpace(val[:i])
			}
		}
		// Unquote a single layer of " or ' if both ends match.
		val = unquote(val)
		if _, exists := out.KV[key]; !exists {
			out.Order = append(out.Order, key)
		}
		out.KV[key] = val
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scanning input: %w", err)
	}
	return out, nil
}

func unquote(s string) string {
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			return s[1 : len(s)-1]
		}
	}
	return s
}

// Result is what Translate returns.  YAML is the rendered
// pg_hardstorage.yaml; Unmapped is the list of "we saw this var
// but had nothing to do with it" entries; Warnings are semantic-
// equivalence notes (algorithm differs, async ignored, ...).
type Result struct {
	YAML     string
	Unmapped []string
	Warnings []string
}

// Translate converts a parsed env file into a pg_hardstorage YAML
// document.  Each WAL-G env file describes exactly one repo, so
// exactly one deployment is emitted.  The deployment name comes
// from PG_HARDSTORAGE_DEPLOYMENT, PGHOST, or "default" (matching
// the runtime resolution in compat/walg/flags.go).
func Translate(env *EnvFile) (*Result, error) {
	if env == nil {
		return &Result{}, nil
	}
	out := &Result{}

	var b strings.Builder
	b.WriteString("# Generated by pg_hardstorage compat translate --from walg\n")
	b.WriteString("# Review every block before activating; semantic notes are above each line.\n")
	b.WriteString("\n")
	b.WriteString("deployments:\n")

	name := env.KV["PG_HARDSTORAGE_DEPLOYMENT"]
	if name == "" {
		name = env.KV["PGHOST"]
	}
	if name == "" {
		name = "default"
	}
	// Strip any port artefact from PGHOST.
	if i := strings.IndexAny(name, ":/"); i >= 0 {
		name = name[:i]
	}
	fmt.Fprintf(&b, "  - name: %s\n", name)

	// PG connection
	if host := env.KV["PGHOST"]; host != "" {
		user := env.KV["PGUSER"]
		if user == "" {
			user = "postgres"
		}
		port := env.KV["PGPORT"]
		db := env.KV["PGDATABASE"]
		if db == "" {
			db = "postgres"
		}
		hostport := host
		if port != "" {
			hostport = host + ":" + port
		}
		u := url.URL{
			Scheme: "postgres",
			User:   url.User(user),
			Host:   hostport,
			Path:   "/" + db,
		}
		fmt.Fprintf(&b, "    pg_connection: %q\n", u.String())
	}

	// Repository — exactly one of WALG_*_PREFIX should be set.
	repoCount := 0
	for _, k := range []string{"WALG_S3_PREFIX", "WALG_GS_PREFIX", "WALG_AZURE_PREFIX", "WALG_FILE_PREFIX", "WALG_SSH_PREFIX"} {
		if env.KV[k] != "" {
			repoCount++
		}
	}
	if repoCount > 1 {
		out.Warnings = append(out.Warnings,
			"["+name+"] multiple WALG_*_PREFIX vars set; pick exactly one before activating")
	}
	switch {
	case env.KV["WALG_S3_PREFIX"] != "":
		fmt.Fprintf(&b, "    repo: %q\n", env.KV["WALG_S3_PREFIX"])
		out.Warnings = append(out.Warnings,
			"["+name+"] AWS credentials must be supplied via the standard SDK chain (env, IRSA, profile)")
	case env.KV["WALG_GS_PREFIX"] != "":
		fmt.Fprintf(&b, "    repo: %q\n", env.KV["WALG_GS_PREFIX"])
	case env.KV["WALG_AZURE_PREFIX"] != "":
		fmt.Fprintf(&b, "    repo: %q\n", env.KV["WALG_AZURE_PREFIX"])
	case env.KV["WALG_FILE_PREFIX"] != "":
		path := env.KV["WALG_FILE_PREFIX"]
		if !strings.HasPrefix(path, "/") {
			out.Unmapped = append(out.Unmapped,
				"["+name+"] WALG_FILE_PREFIX = "+path+" (not absolute — invalid)")
		} else {
			fmt.Fprintf(&b, "    repo: %q\n", "file://"+path)
		}
	case env.KV["WALG_SSH_PREFIX"] != "":
		mapped := strings.Replace(env.KV["WALG_SSH_PREFIX"], "ssh://", "sftp://", 1)
		fmt.Fprintf(&b, "    repo: %q\n", mapped)
		out.Warnings = append(out.Warnings,
			"["+name+"] WALG_SSH_PREFIX mapped to sftp://; verify with `pg_hardstorage doctor`")
	}

	// Encryption — refused, not silently re-encrypted.  We emit
	// a comment block documenting the refusal so the operator
	// reviewing the YAML can wire pg_hardstorage's KMS envelope
	// before activating.
	encrypted := false
	for _, k := range []string{"WALG_LIBSODIUM_KEY", "WALG_GPG_KEY_ID", "WALG_PGP_KEY", "WALG_PGP_KEY_PATH"} {
		if env.KV[k] != "" {
			encrypted = true
			break
		}
	}
	if encrypted {
		fmt.Fprintln(&b, "    # WAL-G encryption (libsodium / GPG / PGP) is not byte-compatible with native AES-256-GCM.")
		fmt.Fprintln(&b, "    # Configure encryption.kek_ref before activating; existing WAL-G backups stay readable by `wal-g`.")
		fmt.Fprintln(&b, "    encryption:")
		fmt.Fprintln(&b, "      kek_ref: \"local:default\"")
		fmt.Fprintln(&b, "      passphrase_env: PG_HARDSTORAGE_KEK_PASSPHRASE")
		out.Warnings = append(out.Warnings,
			"["+name+"] WAL-G envelope (libsodium/GPG/PGP) is not honoured; configure encryption.kek_ref")
	}

	// Compression
	switch strings.ToLower(env.KV["WALG_COMPRESSION_METHOD"]) {
	case "", "zstd":
		// Native default; no emit.
	case "lz4", "lzma", "brotli":
		fmt.Fprintf(&b,
			"    # WALG_COMPRESSION_METHOD=%s ignored; native uses zstd by default.\n",
			env.KV["WALG_COMPRESSION_METHOD"])
		out.Warnings = append(out.Warnings,
			"["+name+"] WALG_COMPRESSION_METHOD="+env.KV["WALG_COMPRESSION_METHOD"]+" ignored")
	}

	// Per-section unknowns.
	for _, k := range sortedKeys(env.KV) {
		switch k {
		case "PGHOST", "PGPORT", "PGUSER", "PGDATABASE", "PGPASSWORD",
			"WALG_S3_PREFIX", "WALG_GS_PREFIX", "WALG_AZURE_PREFIX",
			"WALG_FILE_PREFIX", "WALG_SSH_PREFIX",
			"WALG_LIBSODIUM_KEY", "WALG_GPG_KEY_ID", "WALG_PGP_KEY", "WALG_PGP_KEY_PATH",
			"WALG_COMPRESSION_METHOD",
			"PG_HARDSTORAGE_DEPLOYMENT":
			// handled above
		default:
			out.Unmapped = append(out.Unmapped,
				fmt.Sprintf("%s = %s", k, env.KV[k]))
		}
	}

	out.YAML = b.String()
	return out, nil
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
